services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    environment:
      API_PORT: 3000
    ports:
      - '3000:3000'

  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    depends_on:
      - api
    ports:
      - '8080:80'
